import { EmployeeProfile, Job, JobCategory, Notification, Review, AvailabilityStatus, Referral, ReferralStatus, EmergencyContact, Language, Currency, Transaction, ClientProfile, Conversation, Message, CorporateProfile, BadgeType, SubscriptionPlan, Timesheet, TimesheetStatus, SupportTicket, TicketStatus, TicketCategory, TicketMessage, TicketPriority, AdminUser, Dispute, DisputeStatus, AuditLog } from './types';

export const mockReviews: Review[] = [
  { id: 1, clientName: 'Tariro M.', rating: 5, comment: 'Excellent service, very professional and punctual.', date: '2024-07-15', status: 'Approved' },
  { id: 2, clientName: 'John D.', rating: 4, comment: 'Good work, but was a bit late on the first day.', date: '2024-06-20', status: 'Approved' },
  { id: 3, clientName: 'Jane S.', rating: 5, comment: 'Fantastic cook! The family loves her meals.', date: '2024-05-10', status: 'Approved' },
  { id: 4, clientName: 'Anonymous', rating: 1, comment: 'This is not a real review, please remove it. It contains bad words.', date: '2024-07-28', status: 'Pending' },
  { id: 5, clientName: 'Peter P.', rating: 2, comment: 'Did not follow instructions properly. I am not happy with the service provided.', date: '2024-07-29', status: 'Pending' },
];

export const mockEmergencyContacts: EmergencyContact[] = [
  { id: 1, name: 'Tafadzwa Moyo (Husband)', phone: '+263 77 123 4567' },
  { id: 2, name: 'Main Office', phone: '+263785458828' },
];

export const mockClients: ClientProfile[] = [
  {
    id: 101,
    name: 'The Moyo Family',
    profilePictureUrl: 'https://picsum.photos/seed/moyofamily/200/200',
    location: 'Borrowdale, Harare',
    bio: 'We are a friendly and busy family of four with two wonderful school-aged children. We are looking for someone who can become a part of our family and help keep our home running smoothly. We value honesty, reliability, and a positive attitude.',
    householdDetails: { adults: 2, children: 2, pets: '1 friendly Labrador' },
    preferredLanguage: Language.English,
    subscription: SubscriptionPlan.Basic,
    memberSince: '2023-05-12',
    hiredEmployeeIds: [],
    hasPaidForAccess: false,
    viewedProfileCount: 4,
    accessStartDate: null,
  },
  {
    id: 102,
    name: 'Mr. Chikwanda',
    profilePictureUrl: 'https://picsum.photos/seed/chikwanda/200/200',
    location: 'Harare CBD',
    bio: 'I am a busy executive looking for a professional and discreet driver for corporate and personal travel. Punctuality and knowledge of the city are paramount.',
    householdDetails: { adults: 1, children: 0, pets: 'None' },
    preferredLanguage: Language.English,
    subscription: SubscriptionPlan.Premium,
    memberSince: '2022-11-01',
    hiredEmployeeIds: [],
    hasPaidForAccess: true,
    viewedProfileCount: 1,
    accessStartDate: new Date().toISOString(),
  },
   {
    id: 103,
    name: 'The Banda Family',
    profilePictureUrl: 'https://picsum.photos/seed/bandafamily/200/200',
    location: 'Hillside, Bulawayo',
    bio: 'We are a retired couple seeking a part-time cook to help with daily meals. We enjoy healthy, home-cooked food and appreciate someone with a passion for cooking.',
    householdDetails: { adults: 2, children: 0, pets: 'None' },
    preferredLanguage: Language.Ndebele,
    subscription: SubscriptionPlan.Basic,
    memberSince: '2024-01-20',
    hiredEmployeeIds: [],
    hasPaidForAccess: false,
    viewedProfileCount: 0,
    accessStartDate: null,
  },
  {
    id: 104,
    name: 'The Smith Family',
    profilePictureUrl: 'https://picsum.photos/seed/smithfamily/200/200',
    location: 'London, UK',
    bio: 'We are a British family living in London, looking for a reliable and experienced live-in maid from Zimbabwe to help manage our busy household. We have two children and are looking for someone to join our family long-term.',
    householdDetails: { adults: 2, children: 2, pets: '1 small dog' },
    preferredLanguage: Language.English,
    subscription: SubscriptionPlan.Premium,
    memberSince: '2024-07-30',
    hiredEmployeeIds: [],
    hasPaidForAccess: true,
    viewedProfileCount: 0,
    accessStartDate: new Date().toISOString(),
  }
];

export const mockClient: ClientProfile = mockClients[0];


export const mockCorporateClients: CorporateProfile[] = [
  {
    id: 201,
    companyName: 'First Bank Zimbabwe',
    industry: 'Finance',
    locations: ['Harare CBD Branch', 'Bulawayo Main Branch', 'Mutare Branch'],
  },
  {
    id: 202,
    companyName: 'Sunshine Hotels Group',
    industry: 'Hospitality',
    locations: ['Harare Grand Hotel', 'Victoria Falls Resort'],
  },
];


export const mockEmployees: EmployeeProfile[] = [
  {
    id: 1,
    name: 'Rutendo Moyo',
    role: JobCategory.Maid,
    age: 28,
    religion: 'Christian',
    location: 'Harare',
    experience: 5,
    rating: 4.8,
    reviews: mockReviews.filter(r => r.status === 'Approved'),
    bio: 'A dedicated and hardworking maid with over 5 years of experience in housekeeping and childcare. I am reliable, trustworthy, and pay great attention to detail.',
    skills: ['Deep Cleaning', 'Laundry', 'Ironing', 'Basic Childcare'],
    certifications: ['Housekeeping Diploma', 'First Aid Certificate'],
    availability: AvailabilityStatus.FullTime,
    languages: ['Shona', 'English'],
    verified: true,
    backgroundChecked: true,
    policeClearanceVerified: true,
    referenceChecked: true,
    medicalClearance: false,
    hasDriversLicense: true,
    hasDegreeOrDiploma: false,
    desiredSalary: 300,
    desiredOffDays: 4,
    referralCode: 'RUT-M-58X3',
    profilePictureUrl: 'https://picsum.photos/seed/rutendo/400/400',
    videoIntroductionUrl: 'https://storage.googleapis.com/web-dev-assets/video-and-source-tags/chrome.mp4',
    emergencyContacts: mockEmergencyContacts,
    preferredLanguage: Language.Shona,
    completedJobs: 15,
    badges: [BadgeType.TopRated, BadgeType.FivePlusJobsCompleted, BadgeType.ReferralStar, BadgeType.PoliceClearanceVerified, BadgeType.ReferenceChecked],
    documents: [
        { type: 'ID', url: '/docs/id-rutendo.pdf', status: 'Approved' },
        { type: 'Police Clearance', url: '/docs/police-rutendo.pdf', status: 'Approved' },
        { type: 'Medical Certificate', url: '/docs/medical-rutendo.pdf', status: 'Pending' },
    ],
  },
  {
    id: 2,
    name: 'Tendai Banda',
    role: JobCategory.Cook,
    age: 35,
    religion: 'Christian',
    location: 'Bulawayo',
    experience: 8,
    rating: 4.9,
    reviews: [mockReviews[2]],
    bio: 'Professional cook with a passion for creating delicious and healthy meals. Specializing in traditional Zimbabwean cuisine and international dishes.',
    skills: ['Meal Planning', 'Baking', 'Grilling', 'Traditional Zimbabwean Cuisine'],
    certifications: ['Advanced Culinary Arts Certificate'],
    availability: AvailabilityStatus.PartTime,
    languages: ['Ndebele', 'English'],
    verified: true,
    backgroundChecked: false,
    policeClearanceVerified: false,
    referenceChecked: false,
    medicalClearance: false,
    hasDriversLicense: false,
    hasDegreeOrDiploma: true,
    desiredSalary: 400,
    desiredOffDays: 8,
    referralCode: 'TEN-B-91Y7',
    profilePictureUrl: 'https://picsum.photos/seed/tendai/400/400',
    emergencyContacts: [],
    preferredLanguage: Language.English,
    completedJobs: 8,
    badges: [BadgeType.TopRated, BadgeType.FivePlusJobsCompleted],
    documents: [
      { type: 'ID', url: '/docs/id-tendai.pdf', status: 'Approved' },
    ],
  },
  {
    id: 3,
    name: 'Farai Chikwaka',
    role: JobCategory.Driver,
    age: 42,
    religion: 'Christian',
    location: 'Harare',
    experience: 10,
    rating: 4.7,
    reviews: [],
    bio: 'Experienced and professional driver with a clean driving record. I am familiar with all routes in Harare and surrounding areas. Safety is my top priority.',
    skills: ['Defensive Driving', 'Vehicle Maintenance', 'Navigation'],
    certifications: [],
    availability: AvailabilityStatus.FullTime,
    languages: ['English', 'Shona'],
    verified: true,
    backgroundChecked: true,
    policeClearanceVerified: false,
    referenceChecked: false,
    medicalClearance: false,
    hasDriversLicense: true,
    hasDegreeOrDiploma: false,
    desiredSalary: 500,
    desiredOffDays: 4,
    referralCode: 'FAR-C-12Z6',
    profilePictureUrl: 'https://picsum.photos/seed/farai/400/400',
    emergencyContacts: [],
    preferredLanguage: Language.English,
    completedJobs: 22,
    badges: [BadgeType.FivePlusJobsCompleted],
    documents: [
      { type: 'ID', url: '/docs/id-farai.pdf', status: 'Approved' },
      { type: 'Police Clearance', url: '/docs/police-farai.pdf', status: 'Pending' },
    ],
  },
  {
    id: 4,
    name: 'Chipo Dube',
    role: JobCategory.NurseAide,
    age: 25,
    religion: 'Christian',
    location: 'Mutare',
    experience: 4,
    rating: 5.0,
    reviews: [],
    bio: 'Compassionate and certified Nurse Aide with experience in elderly care and post-operative support. Patient, caring, and highly skilled in monitoring vital signs and assisting with daily activities.',
    skills: ['Elderly Care', 'Medication Reminders', 'Mobility Assistance', 'Patient Monitoring'],
    certifications: ['Certified Nursing Assistant (CNA)', 'CPR Certified', 'First Aid Certificate'],
    availability: AvailabilityStatus.Contract,
    languages: ['English', 'Shona'],
    verified: false,
    backgroundChecked: false,
    policeClearanceVerified: false,
    referenceChecked: false,
    medicalClearance: false,
    hasDriversLicense: false,
    hasDegreeOrDiploma: true,
    desiredSalary: 450,
    desiredOffDays: 6,
    referralCode: 'CHI-D-45A1',
    profilePictureUrl: 'https://picsum.photos/seed/chipo/400/400',
    emergencyContacts: [],
    preferredLanguage: Language.English,
    completedJobs: 3,
    badges: [BadgeType.TopRated],
    documents: [
       { type: 'ID', url: '/docs/id-chipo.pdf', status: 'Pending' },
       { type: 'Medical Certificate', url: '/docs/medical-chipo.pdf', status: 'Pending' },
    ],
  },
   {
    id: 5,
    name: 'Mufaro Gumbo',
    role: JobCategory.Cleaner,
    age: 22,
    religion: 'Apostolic',
    location: 'Harare',
    experience: 3,
    rating: 4.5,
    reviews: [],
    bio: 'Efficient and thorough cleaner for both residential and commercial spaces. I bring my own eco-friendly cleaning supplies.',
    skills: ['Residential Cleaning', 'Office Cleaning', 'Window Washing'],
    certifications: [],
    availability: AvailabilityStatus.PartTime,
    languages: ['Shona'],
    verified: true,
    backgroundChecked: false,
    policeClearanceVerified: false,
    referenceChecked: false,
    medicalClearance: false,
    hasDriversLicense: false,
    hasDegreeOrDiploma: false,
    desiredSalary: 250,
    desiredOffDays: 10,
    referralCode: 'MUF-G-33B9',
    profilePictureUrl: 'https://picsum.photos/seed/mufaro/400/400',
    emergencyContacts: [],
    preferredLanguage: Language.Shona,
    completedJobs: 6,
    badges: [BadgeType.FivePlusJobsCompleted],
    documents: [],
  },
  {
    id: 6,
    name: 'Thabo Ncube',
    role: JobCategory.Chef,
    age: 38,
    religion: 'Not Specified',
    location: 'Victoria Falls',
    experience: 12,
    rating: 4.9,
    reviews: [],
    bio: 'Internationally trained chef specializing in fusion cuisine. Available for private events, dinner parties, and consultancy.',
    skills: ['Fine Dining', 'Pastry', 'Menu Development', 'Event Catering'],
    certifications: ['Le Cordon Bleu Diploma'],
    availability: AvailabilityStatus.Contract,
    languages: ['English', 'French', 'Ndebele'],
    verified: true,
    backgroundChecked: true,
    policeClearanceVerified: true,
    referenceChecked: true,
    medicalClearance: true,
    hasDriversLicense: true,
    hasDegreeOrDiploma: true,
    desiredSalary: 800,
    desiredOffDays: 8,
    referralCode: 'THA-N-78C2',
    profilePictureUrl: 'https://picsum.photos/seed/thabo/400/400',
    videoIntroductionUrl: 'https://storage.googleapis.com/web-dev-assets/video-and-source-tags/chrome.mp4',
    emergencyContacts: [],
    preferredLanguage: Language.English,
    completedJobs: 11,
    badges: [BadgeType.TopRated, BadgeType.FivePlusJobsCompleted, BadgeType.EliteWorker, BadgeType.PoliceClearanceVerified, BadgeType.ReferenceChecked, BadgeType.MedicalClearance],
    documents: [],
  },
  {
    id: 7,
    name: 'Tinashe Chari',
    role: JobCategory.Maid,
    age: 31,
    religion: 'Christian',
    location: 'Avondale, Harare',
    experience: 6,
    rating: 4.9,
    reviews: mockReviews.filter(r => r.status === 'Approved'),
    bio: 'A highly organized and professional household manager with a diploma in hospitality. Experienced in managing busy households, providing exceptional cleaning, and childcare. Possesses a clean driver\'s license and is first aid certified.',
    skills: ['Household Management', 'Advanced Cleaning', 'Child Supervision', 'Cooking', 'Driving'],
    certifications: ['First Aid Certificate', 'Housekeeping Certificate', 'Diploma in Hospitality Management'],
    availability: AvailabilityStatus.FullTime,
    languages: ['English', 'Shona'],
    verified: true,
    backgroundChecked: true,
    policeClearanceVerified: true,
    referenceChecked: true,
    medicalClearance: true,
    hasDriversLicense: true,
    hasDegreeOrDiploma: true,
    desiredSalary: 450,
    desiredOffDays: 4,
    referralCode: 'TIN-C-45B2',
    profilePictureUrl: 'https://picsum.photos/seed/tinashe/400/400',
    emergencyContacts: [],
    preferredLanguage: Language.English,
    completedJobs: 18,
    badges: [BadgeType.TopRated, BadgeType.PremiumEmployee, BadgeType.PoliceClearanceVerified, BadgeType.ReferenceChecked, BadgeType.MedicalClearance],
    documents: [],
  },
  {
    id: 8,
    name: 'Sipho Ndlovu',
    role: JobCategory.Gardener,
    age: 33,
    religion: 'Christian',
    location: 'Gweru',
    experience: 7,
    rating: 0,
    reviews: [],
    bio: 'Experienced gardener with a passion for creating beautiful and sustainable outdoor spaces. Skilled in lawn care, planting, and irrigation systems.',
    skills: ['Landscaping', 'Lawn Maintenance', 'Pruning', 'Irrigation'],
    certifications: ['Horticulture Certificate'],
    availability: AvailabilityStatus.AvailableImmediately,
    languages: ['Ndebele', 'English'],
    verified: false,
    backgroundChecked: false,
    policeClearanceVerified: false,
    referenceChecked: false,
    medicalClearance: false,
    hasDriversLicense: false,
    hasDegreeOrDiploma: true,
    desiredSalary: 350,
    desiredOffDays: 4,
    referralCode: 'SIP-N-67D4',
    profilePictureUrl: 'https://picsum.photos/seed/sipho/400/400',
    emergencyContacts: [],
    preferredLanguage: Language.Ndebele,
    completedJobs: 0,
    badges: [],
    documents: [],
},
{
    id: 9,
    name: 'Blessing Chauke',
    role: JobCategory.SecurityGuard,
    age: 45,
    religion: 'Christian',
    location: 'Harare CBD',
    experience: 15,
    rating: 4.6,
    reviews: [],
    bio: 'Highly experienced and vigilant security professional with a background in corporate security. Certified and trained in emergency response and conflict resolution.',
    skills: ['Patrolling', 'Access Control', 'CCTV Monitoring', 'Emergency Response', 'Conflict Resolution'],
    certifications: ['Security Guard Training Certificate', 'First Aid & CPR'],
    availability: AvailabilityStatus.FullTime,
    languages: ['English', 'Shona'],
    verified: true,
    backgroundChecked: true,
    policeClearanceVerified: true,
    referenceChecked: true,
    medicalClearance: false,
    hasDriversLicense: false,
    hasDegreeOrDiploma: false,
    desiredSalary: 550,
    desiredOffDays: 4,
    referralCode: 'BLE-C-99E5',
    profilePictureUrl: 'https://picsum.photos/seed/blessing/400/400',
    emergencyContacts: [],
    preferredLanguage: Language.English,
    completedJobs: 30,
    badges: [BadgeType.FivePlusJobsCompleted, BadgeType.PoliceClearanceVerified, BadgeType.ReferenceChecked],
    documents: [],
  },
  {
    id: 10,
    name: 'Nyarai Dube',
    role: JobCategory.BabyMinder,
    age: 26,
    religion: 'Christian',
    location: 'Mount Pleasant, Harare',
    experience: 4,
    rating: 4.9,
    reviews: [],
    bio: 'A warm, caring, and responsible baby minder with 4 years of experience caring for infants and toddlers. I am certified in pediatric first aid and CPR. I love creating a safe and stimulating environment for children to grow.',
    skills: ['Infant Care', 'Toddler Activities', 'Meal Preparation for Children', 'Pediatric First Aid', 'CPR Certified'],
    certifications: ['Pediatric First Aid Certificate', 'CPR Certificate', 'Early Childhood Development Certificate'],
    availability: AvailabilityStatus.PartTime,
    languages: ['English', 'Shona'],
    verified: true,
    backgroundChecked: true,
    policeClearanceVerified: true,
    referenceChecked: true,
    medicalClearance: true,
    hasDriversLicense: false,
    hasDegreeOrDiploma: true,
    desiredSalary: 380,
    desiredOffDays: 8,
    referralCode: 'NYA-D-88F1',
    profilePictureUrl: 'https://picsum.photos/seed/nyarai/400/400',
    emergencyContacts: [],
    preferredLanguage: Language.English,
    completedJobs: 9,
    badges: [BadgeType.TopRated, BadgeType.FivePlusJobsCompleted, BadgeType.PoliceClearanceVerified, BadgeType.ReferenceChecked, BadgeType.MedicalClearance],
    documents: [],
  },
];

export const mockJobs: Job[] = [
  {
    id: 1,
    clientId: 101,
    title: 'Full-time Maid for a Family of Four',
    category: JobCategory.Maid,
    clientName: 'The Moyo Family',
    location: 'Borrowdale, Harare',
    salary: 350,
    duration: 'Long-term',
    description: 'We are looking for an experienced and trustworthy maid for general housekeeping, laundry, and assisting with two school-aged children. Must be good with kids and have verifiable references.',
    postedDate: '2024-07-20',
    currency: Currency.USD,
    numberOfKids: 2,
    agesOfKids: '6, 10',
    duties: ['General Housekeeping', 'Laundry', 'Cooking for kids', 'School run assistance'],
    numberOfRooms: 5,
  },
  {
    id: 2,
    clientId: 102,
    title: 'Private Driver for Executive',
    category: JobCategory.Driver,
    clientName: 'Mr. Chikwanda',
    location: 'Harare CBD',
    salary: 500,
    duration: 'Long-term',
    description: 'Seeking a professional and discreet driver for an executive. Must have a valid Class 2 license, extensive knowledge of Harare, and be flexible with hours.',
    postedDate: '2024-07-18',
    currency: Currency.USD,
  },
  {
    id: 3,
    clientId: 103,
    title: 'Part-time Cook for Elderly Couple',
    category: JobCategory.Cook,
    clientName: 'The Banda Family',
    location: 'Hillside, Bulawayo',
    salary: 20, // Per hour
    hourlyRate: 20,
    duration: 'Short-term',
    description: 'Looking for a cook to prepare healthy and delicious lunches and dinners, 5 days a week. Experience with low-sodium and diabetic-friendly meals is a plus.',
    postedDate: '2024-07-15',
    currency: Currency.ZAR,
  },
   {
    id: 4,
    clientId: 101,
    title: 'Weekend Nurse Aide for Grandfather',
    category: JobCategory.NurseAide,
    clientName: 'S. Dube',
    location: 'Mutare',
    salary: 150000,
    duration: 'Long-term',
    description: 'Need a compassionate nurse aide to assist my elderly grandfather on Saturdays and Sundays. Duties include companionship, medication reminders, and light meal preparation.',
    postedDate: '2024-07-21',
    currency: Currency.RTGS,
  },
   {
    id: 5,
    clientId: 102,
    title: 'One-time Deep Clean for Apartment',
    category: JobCategory.Cleaner,
    clientName: 'T. Ncube',
    location: 'Avondale, Harare',
    salary: 80,
    duration: 'One-time',
    description: 'Require a thorough deep clean for a 2-bedroom apartment before moving in. All cleaning supplies will be provided.',
    postedDate: '2024-07-22',
    currency: Currency.USD,
    numberOfRooms: 4,
    duties: ['Window washing', 'Floor scrubbing', 'Kitchen deep clean', 'Bathroom sanitization'],
  },
  {
    id: 6,
    clientId: 101,
    title: 'Full-time Maid needed urgently',
    category: JobCategory.Maid,
    clientName: 'The Jones Family',
    location: 'Avondale, Harare',
    salary: 400,
    duration: 'Long-term',
    description: 'Urgently seeking an experienced maid for a busy household. Must be reliable and have good references.',
    postedDate: '2024-07-24',
    currency: Currency.USD,
    numberOfKids: 3,
    agesOfKids: '2, 5, 9',
    duties: ['Deep cleaning', 'Childcare', 'Ironing'],
    numberOfRooms: 6,
  },
  {
    id: 7,
    clientId: 103,
    title: 'Weekend Cook for Family Gatherings',
    category: JobCategory.Cook,
    clientName: 'The Khumalo Family',
    location: 'Burnside, Bulawayo',
    salary: 1800,
    hourlyRate: 30,
    duration: 'Short-term',
    description: 'We are looking for a creative cook to prepare meals for weekend family events. Must be skilled in traditional Zimbabwean dishes and be able to cater for up to 15 people.',
    postedDate: '2024-07-25',
    currency: Currency.ZAR,
  },
  {
    id: 8,
    clientId: 201, // Corporate Client ID
    title: 'Corporate Cleaner for Bank Branch',
    category: JobCategory.Cleaner,
    clientName: 'First Bank Zimbabwe',
    location: 'Harare CBD Branch',
    salary: 450,
    duration: 'Long-term',
    description: 'Seeking a team of 3 professional cleaners for daily maintenance of our CBD branch. Must be reliable and work to a high standard. Previous corporate cleaning experience preferred.',
    postedDate: '2024-07-26',
    currency: Currency.USD,
  },
  {
    id: 9,
    clientId: 202, // Corporate Client ID
    title: 'Hotel Gardener & Landscaper',
    category: JobCategory.Gardener,
    clientName: 'Sunshine Hotels Group',
    location: 'Victoria Falls Resort',
    salary: 600,
    duration: 'Long-term',
    description: 'Full-time gardener needed to maintain the resort grounds, including flower beds, lawns, and water features. Must have experience with tropical plants.',
    postedDate: '2024-07-25',
    currency: Currency.USD,
  },
  {
    id: 10,
    clientId: 201, // Corporate Client ID
    title: 'Night Shift Security Guard',
    category: JobCategory.SecurityGuard,
    clientName: 'First Bank Zimbabwe',
    location: 'Harare CBD Branch',
    salary: 600,
    duration: 'Long-term',
    description: 'We are seeking a reliable and alert security guard for the night shift at our main branch. Responsibilities include monitoring surveillance equipment, patrolling the premises, and ensuring the safety and security of our facility.',
    postedDate: '2024-07-27',
    currency: Currency.USD,
  },
  {
    id: 11,
    clientId: 101, // The Moyo Family
    title: 'Part-time Baby Minder for Infant',
    category: JobCategory.BabyMinder,
    clientName: 'The Moyo Family',
    location: 'Borrowdale, Harare',
    salary: 250,
    duration: 'Long-term',
    description: 'We are seeking a caring and experienced baby minder for our 6-month-old infant. The role is part-time, 3 days a week. Must have experience with infants and be first-aid certified.',
    postedDate: '2024-07-28',
    currency: Currency.USD,
    numberOfKids: 1,
    agesOfKids: '6 months',
    duties: ['Infant feeding and care', 'Light laundry for baby', 'Engaging in developmental activities'],
  },
  {
    id: 12,
    clientId: 104, // new client's ID
    title: 'Live-in Maid for Family in London',
    category: JobCategory.Maid,
    clientName: 'The Smith Family',
    location: 'London, UK',
    salary: 1500,
    duration: 'Long-term',
    description: 'Seeking an experienced and caring live-in maid to assist with housekeeping, laundry, and cooking for a family of four in London. This is a great opportunity for someone looking to work abroad. All visa and travel costs will be covered for the right candidate.',
    postedDate: '2024-07-30',
    currency: Currency.USD,
    numberOfKids: 2,
    agesOfKids: '7, 11',
    duties: ['Full Housekeeping', 'Laundry & Ironing', 'Family Cooking', 'Errands'],
    numberOfRooms: 8,
  },
];

export const mockNotifications: Notification[] = [
  { id: 5, text: "New job matching your profile: 'Weekend Cook for Family Gatherings'.", date: '2024-07-25', read: false },
  { id: 4, text: "New job matching your profile: 'Full-time Maid needed urgently'.", date: '2024-07-24', read: false },
  { id: 1, text: 'Your application for "Full-time Maid" was viewed by The Moyo Family.', date: '2024-07-23', read: false },
  { id: 2, text: 'New job matching your skills: "Weekend Nurse Aide".', date: '2024-07-22', read: false },
  { id: 3, text: 'Welcome to Zimbabwe Maids Centre! Complete your profile to attract clients.', date: '2024-07-21', read: true },
];

export const mockReferrals: Referral[] = [
  { id: 1, refereeName: 'Tatenda Chiwara', status: ReferralStatus.Completed, reward: 5, date: '2024-07-10' },
  { id: 2, refereeName: 'Grace Mutasa', status: ReferralStatus.Completed, reward: 5, date: '2024-06-22' },
  { id: 3, refereeName: 'Peter Moyo', status: ReferralStatus.Pending, reward: 5, date: '2024-07-25' },
];

export let mockTransactions: Transaction[] = [
    { id: 1, date: '2024-07-15', description: 'Payment to Rutendo Moyo', amount: 350, currency: Currency.USD, status: 'Completed', type: 'Hire' },
    { id: 2, date: '2024-07-10', description: 'Payment to Farai Chikwaka', amount: 100, currency: Currency.USD, status: 'Completed', type: 'Hire', refundStatus: 'Requested' },
    { id: 3, date: '2024-07-05', description: 'Payment to Tendai Banda', amount: 2500, currency: Currency.ZAR, status: 'Completed', type: 'Hire' },
    { id: 4, date: '2024-07-25', description: 'Payment to Chipo Dube', amount: 150000, currency: Currency.RTGS, status: 'Pending', type: 'Hire' },
    { id: 5, date: '2024-07-24', description: 'Payment to Thabo Ncube', amount: 500, currency: Currency.USD, status: 'Failed', type: 'Hire' },
    { id: 6, date: '2024-07-28', description: 'Placement fee for Tinashe Chari', amount: 120, currency: Currency.USD, status: 'Pending', type: 'Hire' },
    { id: 8, date: '2024-07-29', description: 'Once-off hire fee for Sipho Ndlovu', amount: 20, currency: Currency.USD, status: 'Completed', type: 'Hire' },
];

export const mockTimesheets: Timesheet[] = [
  {
    id: 1,
    jobId: 3,
    employeeId: 2,
    employeeName: 'Tendai Banda',
    hoursWorked: 16,
    startDate: '2024-07-18',
    endDate: '2024-07-25',
    totalAmount: 320, // 16 hours * R20/hr
    currency: Currency.ZAR,
    status: TimesheetStatus.Pending,
  },
  {
    id: 2,
    jobId: 7,
    employeeId: 1,
    employeeName: 'Rutendo Moyo',
    hoursWorked: 8,
    startDate: '2024-07-20',
    endDate: '2024-07-21',
    totalAmount: 240, // 8 hours * R30/hr
    currency: Currency.ZAR,
    status: TimesheetStatus.Approved,
  }
];


const chatMessages: Message[] = [
  { id: 1, senderId: 101, text: "Hello, are you available for an interview this week?", timestamp: "10:30 AM", language: Language.English },
  { id: 2, senderId: 1, text: "Mangwanani. Ehe, ndiripo. Ndeipi nguva yakanaka kwamuri?", timestamp: "10:32 AM", language: Language.Shona },
  { id: 3, senderId: 101, text: "Great. How about Wednesday at 2 PM?", timestamp: "10:35 AM", language: Language.English },
  { id: 4, senderId: 1, text: "Zvanaka, Wednesday na 2 PM yakanaka. Tichataura ipapo.", timestamp: "10:37 AM", language: Language.Shona },
];

export const mockConversation: Conversation = {
  id: 1,
  clientId: mockClient.id,
  employeeId: mockEmployees[0].id,
  messages: chatMessages,
};

export const ACCESS_FEE = 10;
export const PROFILE_VIEW_LIMIT = 4;
export const ACCESS_PERIOD_DAYS = 30;

export const paymentDetails = {
  paypal: {
    email: 'cchenje@gmail.com',
  },
  mobileMoney: {
    name: 'Ecocash / Inbucks',
    account: '+263785458828 (Chenjerai)',
    instructions: 'Please send the exact amount and include the purpose (e.g., Access Fee) in the reference.'
  },
  international: {
    name: 'International (Credit Card, Mukuru, WorldRemit)',
    instructions: 'For Credit Card, Mukuru, or WorldRemit, get details via WhatsApp at +263785458828.'
  },
  cash: {
    name: 'Cash Collection',
    address: 'Block 10 Willowvale, Harare, Zimbabwe',
    instructions: 'Please call +263785458828 to schedule a payment collection at our office.'
  },
  confirmationInstructions: 'IMPORTANT: After paying, send proof of payment to +263785458828 on WhatsApp to receive your confirmation code. You must enter this code to complete your transaction.'
};

export const mockTicketMessages: TicketMessage[] = [
    { id: 1, author: 'User', text: 'My profile picture is not updating after I upload a new one. Can you please look into this?', timestamp: '2024-07-28 10:00 AM' },
    { id: 2, author: 'Admin', text: 'Hi, thanks for reaching out. We are looking into the issue and will get back to you shortly. Can you confirm which browser you are using?', timestamp: '2024-07-28 10:15 AM' },
    { id: 3, author: 'User', text: 'I am using Google Chrome.', timestamp: '2024-07-28 10:20 AM' },
];

export const mockAdmins: AdminUser[] = [
    { id: 901, name: 'Admin Tino' },
    { id: 902, name: 'Admin Sam' },
];


export const mockSupportTickets: SupportTicket[] = [
  {
    id: 1001,
    userId: 4, // Chipo Dube
    subject: 'Profile picture not updating',
    category: TicketCategory.TechnicalIssue,
    status: TicketStatus.InProgress,
    priority: TicketPriority.High,
    assignedAdminId: 901,
    createdAt: '2024-07-28',
    lastUpdated: '2024-07-28',
    messages: mockTicketMessages,
  },
  {
    id: 1002,
    userId: 103, // The Banda Family
    subject: 'Question about payment for job #3',
    category: TicketCategory.PaymentQuery,
    status: TicketStatus.Open,
    priority: TicketPriority.Medium,
    createdAt: '2024-07-27',
    lastUpdated: '2024-07-27',
    messages: [
      { id: 1, author: 'User', text: 'I completed the job for the Banda Family but have not received payment. Can you please advise?', timestamp: '2024-07-27 02:30 PM' },
    ],
  },
   {
    id: 1003,
    userId: 2, // Tendai Banda
    subject: 'Complaint regarding a client',
    category: TicketCategory.Complaint,
    status: TicketStatus.Closed,
    priority: TicketPriority.Low,
    assignedAdminId: 902,
    createdAt: '2024-07-20',
    lastUpdated: '2024-07-22',
    messages: [
       { id: 1, author: 'User', text: 'The client was asking me to do tasks that were not in the job description.', timestamp: '2024-07-20 09:00 AM' },
       { id: 2, author: 'Admin', text: 'Thank you for your feedback. We have spoken to the client and addressed the issue.', timestamp: '2024-07-22 11:00 AM' },
    ],
  },
  {
    id: 1004,
    userId: 101, // The Moyo Family
    subject: 'Urgent: Cannot contact hired employee',
    category: TicketCategory.Complaint,
    status: TicketStatus.Open,
    priority: TicketPriority.Urgent,
    createdAt: '2024-07-29',
    lastUpdated: '2024-07-29',
    messages: [
       { id: 1, author: 'User', text: 'I hired Rutendo Moyo yesterday and she was supposed to start today but she is not answering her phone. Can you please assist?', timestamp: '2024-07-29 09:00 AM' },
    ],
  },
];

export const mockDisputes: Dispute[] = [
    {
        id: 201,
        clientId: 101,
        employeeId: 1,
        jobId: 1,
        reason: 'Unsatisfactory Performance',
        clientStatement: 'The employee did not complete the tasks as described in the job post. The house was not cleaned to the standard we agreed upon.',
        employeeStatement: 'The client added many extra tasks that were not originally discussed, and I did not have enough time to complete everything perfectly.',
        status: DisputeStatus.UnderReview,
        createdAt: '2024-07-25',
    },
    {
        id: 202,
        clientId: 102,
        employeeId: 3,
        jobId: 2,
        reason: 'Payment Discrepancy',
        clientStatement: 'The employee is claiming more hours than he actually worked.',
        employeeStatement: 'I worked overtime on three separate days last week due to late meetings, which was approved verbally. The client is refusing to pay for those extra hours.',
        status: DisputeStatus.Open,
        createdAt: '2024-07-28',
    }
];

export const mockAuditLogs: AuditLog[] = [
    { id: 1, timestamp: '2024-07-29 11:45 AM', adminName: 'Admin Tino', action: 'Approved Employee', details: 'Approved profile for Rutendo Moyo (ID: 1)' },
    { id: 2, timestamp: '2024-07-29 10:30 AM', adminName: 'Admin Sam', action: 'Removed Job Posting', details: 'Removed job "Spam Job Post" (ID: 11) for policy violation' },
    { id: 3, timestamp: '2024-07-28 05:15 PM', adminName: 'Admin Sam', action: 'Suspended User', details: 'Suspended client "Bad Client" (ID: 105) due to multiple complaints' },
    { id: 4, timestamp: '2024-07-28 02:00 PM', adminName: 'Admin Tino', action: 'Resolved Dispute', details: 'Marked dispute #201 as Resolved' },
];

export const locationCoordinates: Record<string, { lat: number; lon: number }> = {
  'Borrowdale, Harare': { lat: -17.76, lon: 31.08 },
  'Harare CBD': { lat: -17.82, lon: 31.05 },
  'Hillside, Bulawayo': { lat: -20.17, lon: 28.62 },
  'London, UK': { lat: 51.50, lon: -0.12 },
  'Harare': { lat: -17.82, lon: 31.03 },
  'Bulawayo': { lat: -20.15, lon: 28.58 },
  'Mutare': { lat: -18.97, lon: 32.67 },
  'Avondale, Harare': { lat: -17.79, lon: 31.03 },
  'Victoria Falls': { lat: -17.92, lon: 25.83 },
  'Gweru': { lat: -19.45, lon: 29.82 },
  'Mount Pleasant, Harare': { lat: -17.78, lon: 31.05 },
  'Harare CBD Branch': { lat: -17.82, lon: 31.05 },
  'Victoria Falls Resort': { lat: -17.92, lon: 25.83 },
  'Burnside, Bulawayo': { lat: -20.18, lon: 28.63 },
};

export const getCoordinatesForLocation = (location: string): { lat: number; lon: number } | null => {
  return locationCoordinates[location] || null;
};

export const calculateDistance = (coords1: { lat: number; lon: number }, coords2: { lat: number; lon: number }): number | null => {
  if (!coords1 || !coords2) {
    return null;
  }

  const R = 6371; // Radius of the Earth in km
  const dLat = (coords2.lat - coords1.lat) * (Math.PI / 180);
  const dLon = (coords2.lon - coords1.lon) * (Math.PI / 180);
  const a =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos(coords1.lat * (Math.PI / 180)) * Math.cos(coords2.lat * (Math.PI / 180)) *
    Math.sin(dLon / 2) * Math.sin(dLon / 2);
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  const distance = R * c;
  return Math.round(distance * 10) / 10; // Rounded to one decimal place
};